	--[[THE_INFORMATION_CONTAINED_IN_THIS_FILE_IS_NOT_	INTENDED_TO_BE_DIRECTLY_REVEALED_OR_ANNOUNCED	IN_ANY_WAY_TO_THE_PLAYER_BASE.__THEY_SHOULD_	NOT_BE_ASSISTED_DURING_THE_PROCESS_OF_ACHIEVING	SUCCESS_AGAINST_THIS_CHALLENGE.__FOR_THIS_REASON,	IF_YOU_ARE_A_STAFF_MEMBER_THAT_ALSO_ACTIVELY_PLAYS	IT_IS_SUGGESTED_THAT_YOU_DO_NOT_LOOK_AT_THIS_	FILE_TO_NOT_HAVE_THE_EXPERIENCE_RUINED._	NOTHING_IN_THIS_FILE_IS_REQUIRED_FOR_THE_FUNCTION	OF_THE_PROGRAMMING_BEHIND_IT_AND_FOR_THAT_REASON	IT_DOES_NOT_CONCERN_YOU_ANYWAY.		TL;DR_=_GTFO_OF_THIS_FILE_YOU_CHEATER	-WARP]]--WEAKNESS_TRIGGERSWTRIGS_=_{
--JAS
--COR_109-114
CORSAIR,{ABILITY_FIRE_SHOT,ABILITY_ICE_SHOT,ABILITY_WIND_SHOT",ABILITY_EARTH_SHOT,ABILITY_THUNDER_SHOT,ABILITY_WATER_SHOT	},_
--DNC_
DANCER,{ABILITY_QUICKSTEP,ABILITY_STUTTER_STEP,ABILITY_BOX_STEP,ABILITY_FEATHER_STEP,ABILITY_VIOLENT_FLOURISH,ABILITY_ANIMATED_FLOURISH,ABILITY_DESPERATE_FLOURISH},_
DARK_KNIGHT,{ABILITY_WEAPON_BASH},
DRAGOON,{ABILITY_JUMP,ABILITY_HIGH_JUMP,ABILITY_SPIRIT_JUMP,ABILITY_SOUL_JUMP},
MONK,{ABILITY_CHI_BLAST},
PALADIN,{ABILITY_SHIELD_BASH},
RANGER,{ABILITY_SHADOWBIND},
SCHOLAR,{ABILITY_LIBRA},
THIEF,{ABILITY_BULLY},
WARRIOR,{ABILITY_PROVOKE},
--MAGICBLACK_MAGIC,{PYROHELIX,GEOHELIX,HYDROHELIX,ANEMOHELIX,CRYOHELIX,IONOHELIX,LUMINOHELIX,NOCTOHELIX,FIRE_II,STONE_II,WATER_II,AERO_II,BLIZZARD_II,THUNDER_II,DRAIN,FIRE_III,STONE_III,WATER_III,AERO_III,BLIZZARD_III,THUNDER_III,DRAIN_II,FIRE_IV,STONE_IV,WATER_IV,AERO_IV,BLIZZARD_IV,THUNDER_IV,ASPIR,FIRAGA,STONEGA,WATERGA,AEROGA,BLIZZAGA,THUNDAGA,ASPIR_II,FIRAGA_II,STONEGA_II,WATERGA_II,AEROGA_II,BLIZZAGA_II,THUNDAGA_II,ABSORB-STR,FIRAGA_III,STONEGA_III,WATERGA_III,AEROGA_III,BLIZZAGA_III,THUNDAGA_III,ABSORB-DEX,FIRAJA,STONEJA,WATERJA,AEROJA,BLIZZAJA,THUNDAJA,ABSORB-AGI,FLARE,QUAKE,FLOOD,TORNADO,FREEZE,BURST,ABSORB-VIT,BURN,RASP,DROWN,CHOKE,FROST,SHOCK,ABSORB-INT,POISON,STUN,ABSORB-MND,POISON_II,ABSORB-CHR,POISONGA,ABSORB-TP,ABSORB-ACC,BLIND,DISPEL,BIO_II},WHITE_MAGIC,{ADDLE,SLOW,PARALYZE,BANISH_II,BANISH_III,BANISHGA,BANISHGA_II,HOLY,FLASH,DIA_II,DIAGA},NINJUTSU,{KATON_ICHI,DOTON_ICHI,SUITON_ICHI,HUTON_ICHI,HYOTON_ICHI,RAITON_ICHI,KURAYAMI_ICHI,KATON_NI,DOTON_NI,SUITON_NI,HUTON_NI,HYOTON_NI,RAITON_NI,KURAYAMI_NI,HOJO_ICHI,DOKUMORI_ICHI,JUBAKU_ICHI,YURIN_ICHI,HOJO_NI,AISHA_ICHI	},
BARD_SONGS,{ICE_THRENODY,LIGHTNING_THRENODY,FIRE_THRENODY,EARTH_THRENODY,WIND_THRENODY,WATER_THRENODY,DARK_THRENODY,LIGHT_THRENODY,BATTLEFIELD_ELEGY,MAGIC_FINALE,CARNAGE_ELEGY},
BLUE_MAGIC,{BLASTBOMB,BAD_BREATH,ACRID_STREAM,HECATOMB_WAVE,COLD_WAVE,BLITZSTRAHL,ACTINIC_BURST,DEATH_RAY,FIRESPIT,CIMICINE_DISCHARGE,CORROSIVE_OOZE,LEAFSTORM,FROST_BREATH,CHARGED_WHISKER,BLANK_GAZE,EYES_ON_ME,HEAT_BREATH,MAGNETITE_CLOUD,CURSED_SPHERE,MYSTERIOUS_LIGHT,ICE_BREAK,MIND_BLAST,LIGHT_OF_PENANCE,SANDSPRAY,THERMAL_PULSE,SANDSPIN,MAELSTROM,REAVING_WIND,INFRASONICS,TEMPORAL_SHIFT,RADIANT_BREATH,AWFUL_EYE},
--WEAPON_SKILLS_NON_MYTHIC/RELIC/EMPYREAN/MERIT
WEAPON_SKILLS,{H2H,_DAGGER,_SWORD,_CLUB,_STAFF,_AXE,_GAXE,_GSWD,_SPEAR,_KATANA,_GKT,_BOW,_GUN}
--_PET_MOVES_NON_WYVERN
LIGHT_BLOOD_PACT_CARBUNCLE'S_HOLY_MIST
DARK_BLOOD_PACT_FENRIRS_LUNAR_BAY_OR_DIABOLOSS_NIGHT_TERROR
FIRE_BLOOD_PACT_IFRIT'S_FIRE_IV_(BLOOD_PACT)
ICE_BLOOD_PACT_SHIVA'S_BLIZZARD_IV_(BLOOD_PACT)
WIND_BLOOD_PACT_GARUDA'S_AERO_IV_(BLOOD_PACT)
EARTH_BLOOD_PACT_TITAN'S_STONE_IV_(BLOOD_PACT)
LIGHTNING_BLOOD_PACT_RAMUH'S_THUNDER_IV_(BLOOD_PACT)
WATER_BLOOD_PACT_LEVIATHAN'S_WATER_IV_(BLOOD_PACT)
AUTOMATON_ABILITIES_ANY_AUTOMATION_ABILITY_OR_SPECIAL_ATTACK_TRIGGERS_AN_AUTOMATON_WEAKNESS.
PET_ABILITIES_ANY_CALLED_BEAST'S_SPECIAL_ATTACK_TRIGGERS_A_PET_WEAKNESS.